language: c

before_install:
  - sudo apt-get install -y qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools
  - sudo apt-get install -y build-essential libboost-dev libboost-system-dev
  - sudo apt-get install -y libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev
  - sudo apt-get install -y libssl-dev libdb++-dev

install:
  - qmake
  - make
